edge(user(matteo), user(ele), follow).
edge(user(matteo), user(gabriele), follow).
edge(user(matteo), user(nico), follow).
edge(user(gabriele), user(ele), follow).
edge(user(gabriele), user(matteo), follow).
edge(user(nico), user(ele), follow).
edge(user(matteo), country(italy), lives).
edge(user(gabriele), country(italy), lives).
edge(user(matteo), hobby(running), likes).
edge(user(ele), hobby(swimming), likes).
