edge(user(1), user(2), follow).
edge(user(1), user(3), follow).
edge(user(1), user(4), follow).
edge(user(3), user(2), follow).
edge(user(3), user(1), follow).
edge(user(4), user(2), follow).
edge(user(1), country(italy), lives).
edge(user(3), country(italy), lives).
edge(user(1), hobby(running), likes).
edge(user(2), hobby(swimming), likes).
